### PR TITLE
Updated CardIOVideoStream's delegate to be a UIResponder to fix Xcode 8 compiler error

### PR DESCRIPTION
**Pull request by reidmain**
Detailed explanation of this change is in issue https://github.com/card-io/card.io-iOS-source/issues/69

### CODE REVIEW

**Comment by reidmain** [comment]
I can't figure out how to run unit tests for the project. If I select the `UnitTest` scheme and try to build it I immediately get the build error `CodeSign error: code signing is required for product type 'OCUnit Test Bundle' in SDK 'iOS 9.3'`.

Is there something specific that needs to be configured for the unit tests?

**Comment by josharian** [comment]
LGTM. Leaving to someone else to merge. Don't sweat the tests. For this trivial a change in a heavily used code path, if it compiles and basic functionality works, I'd say it's good.

**Comment by reidmain** [comment]
Cool. I ran the example app on device and was able to recognize a credit card with no issues.

**Comment by reidmain** [comment]
Is there someone we can ping who can merge this PR?

**Comment by josharian** [comment]
@bluk @braebot

**Comment by bluk** [comment]
@reidmain Looks good to me. Thanks for the PR and sorry for the delay.

**Comment by reidmain** [comment]
@bluk no worries. Xcode 8 isn't even GM yet so I understand. If I experience any more issues while trying to integrate this into a Swift 2.3 app I'll open up some more.

**Pull request merged**
