### PR TITLE
Add localization for finnish

### PR DESCRIPTION
**Pull request by JussiSuojanen**
- Created fi.strings file with correct localizations

### CODE REVIEW

**Comment by basssolo** [comment]
This is great! Looks good to me. I did not realize that all I have to do is to add this one localization file. Thanks Jussi!

**Comment by JussiSuojanen** [comment]
I am actually not a 100% sure that the localizations are autogenerated from the files. It might still need to be included in the project file separately. But I am counting on that who ever merges this will add it if it is necessary.

**Comment by JussiSuojanen** [comment]
I can add the comments but the [here] link you provided does not work. I found comments from the CardIOPaymentViewController.h & CardIOView.h that have the languages listed. Are those the only places?

I can make the same change to Android.

**Comment by JussiSuojanen** [comment]
Ok, thanks for the link.  

Btw, I checked the android project.. How do you do the localisation in there? I found the loc files inside the locales folder. But it seems that those generated with a script which I could not find. Also I couldn't find the original localisation files the script seems to use.

**Pull request closed without merging**
